
# GAME
GAME_DEFAULT_BALLS = 1
GAME_DEFAULT_SCREEN_COLOR = (255, 255, 255)
GAME_DEFAULT_SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = (500, 500)
GAME_DEFAULT_FRAME_RATE = 60

# CONTAINER CONSTANTS
CONTAINER_DEFAULT_COLOR = (125, 125, 125)
CONTAINER_DEFAULT_RADIUS = 250
CONTAINER_DEFAULT_THICKNESS = 250
CONTAINER_DEFAULT_CENTER = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)

# BALL CONSTANTS
BALL_DEFAULT_COLOR = (255, 0, 0)
BALL_DEFAULT_RADIUS = 5
