
# GAME
GAME_DEFAULT_BALLS = 10
GAME_DEFAULT_SCREEN_COLOR = (255, 255, 255)
GAME_DEFAULT_SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = (1000, 1000)
GAME_DEFAULT_FRAME_RATE = 120

# CONTAINER CONSTANTS
CONTAINER_DEFAULT_COLOR = (125, 125, 125)
CONTAINER_DEFAULT_RADIUS = 250
CONTAINER_DEFAULT_THICKNESS = 50
CONTAINER_DEFAULT_CENTER = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)
CONTAINER_DEFAULT_VELOCITY = (-300, 0)

# BALL CONSTANTS
BALL_DEFAULT_COLOR = (255, 0, 0)
BALL_DEFAULT_RADIUS = 5
